name: debug-packages

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Choose a tag for the image'
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - latest
          - nightly

env:
  # REGISTRY_SERVER_ADDRESS: ghcr.io/miracleeverywhere/dst-management-platform-api
  REGISTRY_SERVER_ADDRESS: ghcr.io/${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Package Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Get Ref
      id: get-ref
      run: echo "::set-output name=ref::${{ github.ref }}"
    - name: Determine Tags
      id: determine-tags
      run: |
        tags=""
        ref=$(echo ${{ steps.get-ref.outputs.ref }})
        input_tag=$(echo ${{ github.event.inputs.tag }})

        if [[ "$input_tag" != "dev" && "$input_tag" != "" ]]; then
          tags="$input_tag"
        fi

        if [[ "$ref" =~ ^refs\/tags\/v.*$ ]]; then
          tag_name=$(echo "$ref" | sed 's/refs\/tags\///')
          tags="${tags},${tag_name}"
        fi

        # 始终至少有一个标签
        if [[ -z "$tags" ]]; then
          tags="dev"
        fi

        echo "::set-output name=tags::$tags"
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        file: ./docker/Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.REGISTRY_SERVER_ADDRESS }}:${{ steps.determine-tags.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}